language: ruby
rvm:
  - 2.1.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
jdk:
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: oraclejdk7
    - rvm: rbx-2
      jdk: oraclejdk8
  allow_failures:
    - jdk:
      - oraclejdk8
  fast_finish: true
addons:
  code_climate:
    repo_token: e5bf62fa6e2a868829d82468e9a5e425c174c7534bb3c4e681bfb9daf836c8e8
